import React, { createContext, useContext, useState, useMemo, useCallback, useEffect } from 'react'
import AsyncStorage from '@react-native-async-storage/async-storage'

type Language = 'pt-BR' | 'en-US'

const LANGUAGE_STORAGE_KEY = '@cryptohub:language'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  isLoading: boolean
}

const translations = {
  'pt-BR': {
    // Navigation
    'nav.home': 'Início',
    'nav.exchanges': 'Corretoras',
    'nav.strategies': 'Estratégias',
    'nav.profile': 'Perfil',
    
    // Home Screen
    'home.title': 'CryptoHub',
    'home.subtitle': 'Tokens unificados',
    'home.portfolio': 'Total',
    'home.last24h': 'últimas 24h',
    'home.performance': 'Desempenho',
    'home.exchanges': 'Minhas Corretoras',
    'home.noData': 'Sem dados disponíveis',
    'home.loading': 'Carregando dados...',
    'home.distribution': 'Por Exchange',
    'home.exchangeBalances': 'Saldos por Exchange',
    'home.exchangeDetails': 'Detalhes por exchange',
    'home.exchangeHide': 'Ocultar detalhes',
    'home.noExchangesConnected': 'Nenhuma exchange conectada',
    'home.tabSummary': 'Resumo',
    'home.tabAssets': 'Ativos',
    'home.tabOrders': 'Ordens',
    'home.updating': 'Atualizando...',
    
    // Top Gainers/Losers
    'topGainersLosers.gainersTitle': 'Maiores Altas (24h)',
    'topGainersLosers.losersTitle': 'Maiores Baixas (24h)',
    'topGainersLosers.noGainers': 'Nenhuma alta significativa',
    'topGainersLosers.noLosers': 'Nenhuma baixa significativa',
    'topGainersLosers.viewAll': 'Ver todas',
    'topGainersLosers.allGainersTitle': 'Todas as Altas (24h)',
    'topGainersLosers.allLosersTitle': 'Todas as Baixas (24h)',
    'topGainersLosers.total': 'Total',
    'topGainersLosers.tokens': 'tokens',
    
    // Profile Screen
    'profile.title': 'Perfil',
    'profile.subtitle': 'Sua conta',
    'profile.user': 'Usuário do CryptoHub',
    'profile.memberSince': 'Membro desde',
    'profile.settings': 'Configurações',
    'profile.notifications': 'Notificações',
    'profile.security': 'Segurança',
    'profile.language': 'Idioma',
    'profile.languagePt': 'Português (BR)',
    'profile.languageEn': 'English (US)',
    'profile.currency': 'Moeda Preferida',
    'profile.appearance': 'Aparência',
    'profile.darkMode': 'Modo Escuro',
    'profile.enabled': 'Ativado',
    'profile.disabled': 'Desativado',
    'profile.about': 'Sobre',
    'profile.aboutApp': 'Sobre o App',
    'profile.terms': 'Termos de Uso',
    'profile.privacy': 'Privacidade',
    'profile.logout': 'Sair',
    'profile.logoutConfirm': 'Tem certeza que deseja sair?',
    'profile.version': 'Versão',
    'profile.termsOfUse': 'Termos de Uso',
    'profile.privacyPolicy': 'Política de Privacidade',
    'profile.edit': 'Editar',
    'profile.personalInfo': 'INFORMAÇÕES PESSOAIS',
    'profile.email': 'Email',
    'profile.phone': 'Telefone',
    'profile.actions': 'AÇÕES',
    'profile.changePassword': 'Alterar Senha',
    'profile.exportData': 'Exportar Dados',
    
    // Settings Screen
    'settings.title': 'Configurações',
    'settings.subtitle': 'Personalize seu app',
    'settings.systemTitle': 'Sistema',
    'settings.appearance': 'Aparência',
    'settings.notificationsSection': 'Notificações',
    'settings.securitySection': 'Segurança e Privacidade',
    'settings.infoSection': 'Informações',
    'settings.securityModal': 'Segurança',
    'settings.twoFactorAuth': 'Autenticação de Dois Fatores',
    'settings.twoFactorSms': '2FA via SMS',
    'settings.twoFactorSmsDesc': 'Receba códigos de verificação por SMS',
    'settings.googleAuth': 'Google Authenticator',
    'settings.googleAuthDesc': 'Use o app Google Authenticator',
    'settings.autoLock': 'Bloqueio Automático',
    'settings.autoLockEnable': 'Ativar Bloqueio',
    'settings.autoLockDesc': 'Bloquear app após inatividade',
    'settings.inactivityTime': 'Tempo de Inatividade',
    'settings.alerts': 'Alertas',
    'settings.loginAlerts': 'Alertas de Login',
    'settings.loginAlertsDesc': 'Notificar sobre novos logins',
    'settings.activated': 'Ativado',
    'settings.deactivated': 'Desativado',
    'settings.biometricEnabled': 'ativado com sucesso',
    
    // Strategy Screen
    'strategy.title': 'Estratégias',
    'strategy.new': '+ Nova',
    'strategy.strategies': 'estratégias',
    'strategy.strategy': 'estratégia',
    'strategy.executions': 'Execuções',
    'strategy.execution': 'execução',
    'strategy.empty': 'Nenhuma estratégia criada',
    'strategy.emptyDesc': 'Crie sua primeira estratégia automatizada',
    'strategy.executionsEmpty': 'Nenhuma execução registrada',
    'strategy.executionsEmptyDesc': 'As execuções das suas estratégias aparecerão aqui',
    'strategy.noExecutions': 'Nenhuma execução',
    'strategy.executionsWillAppear': 'As ordens executadas aparecerão aqui',
    'strategy.active': 'Ativa',
    'strategy.inactive': 'Inativa',
    'strategy.viewDetails': 'Ver Detalhes',
    'strategy.activate': 'Ativar',
    'strategy.deactivate': 'Desativar',
    'strategy.delete': 'Deletar',
    'strategy.confirmDelete': 'Tem certeza que deseja deletar esta estratégia?',
    'strategy.deleteWarning': 'Esta ação não pode ser desfeita.',
    'strategy.activateConfirm': 'Deseja ativar esta estratégia?',
    'strategy.deactivateConfirm': 'Deseja desativar esta estratégia?',
    'strategy.statusWillChange': 'O status da estratégia será alterado.',
    'strategy.simple': 'Simples',
    'strategy.simpleDesc': 'Estratégia básica (1 TP 5%, SL 2%)',
    'strategy.conservative': 'Conservadora',
    'strategy.conservativeDesc': 'Proteção máxima (2 TPs, trailing stop)',
    'strategy.aggressive': 'Agressiva',
    'strategy.aggressiveDesc': 'Máximo lucro (3 TPs, DCA ativo)',
    'strategy.templates': 'Templates de Estratégia',
    'strategy.templatesSubtitle': 'Detalhes de cada estratégia padrão',
    'strategy.createNew': 'Criar Nova Estratégia',
    'strategy.riskLevel': 'Risco',
    'strategy.configs': 'Configurações',
    'strategy.newStrategy': 'Nova Estratégia',
    'strategy.selectTemplate': 'Selecione uma estratégia pré-configurada',
    'strategy.selectExchange': 'Selecione a exchange',
    'strategy.selectToken': 'Selecione o token',
    'strategy.step': 'Passo',
    'strategy.of': 'de',
    'strategy.chooseTemplate': 'Escolha um template',
    'strategy.chooseExchange': 'Escolha a exchange',
    'strategy.chooseToken': 'Escolha o token',
    'strategy.labelTemplate': 'Template',
    'strategy.labelExchange': 'Exchange',
    'strategy.labelToken': 'Token',
    'strategy.selectExchangeDesc': 'Escolha onde a estratégia será executada',
    'strategy.selectTokenDesc': 'Escolha o token para negociação',
    'strategy.details': 'Detalhes da Estratégia',
    'strategy.notFound': 'Estratégia não encontrada',
    'strategy.errorLoading': 'Erro ao carregar estratégia',
    'strategy.name': 'ESTRATÉGIA',
    'strategy.configuration': 'CONFIGURAÇÕES',
    'strategy.exchange': 'Corretora',
    'strategy.tradingPair': 'Par de Negociação',
    'strategy.template': 'Template',
    'strategy.token': 'Token',
    'strategy.totalExecutions': 'Execuções',
    'strategy.nextCheck': 'Próxima Verificação',
    'strategy.reason': 'Motivo',
    'strategy.buy': 'Compra',
    'strategy.sell': 'Venda',
    'strategy.soon': 'Em breve...',
    'strategy.now': 'Agora',
    'strategy.inOneMinute': 'Em 1 minuto',
    'strategy.in': 'Em',
    'strategy.minutes': 'minutos',
    'strategy.takeProfit': 'TAKE PROFIT',
    'strategy.stopLoss': 'STOP LOSS',
    'strategy.information': 'INFORMAÇÕES',
    'strategy.level': 'Nível',
    'strategy.ofPosition': 'da posição',
    'strategy.whenReaches': 'Quando atingir',
    'strategy.stopAt': 'Para em',
    'strategy.toLimitLosses': 'para limitar perdas',
    'strategy.createdAt': 'Criada em',
    'strategy.lastUpdate': 'Última atualização',
    'strategy.status': 'Status',
    'strategy.statusIdle': 'Ociosa',
    'strategy.statusMonitoring': 'Monitorando',
    'strategy.statusBuyPending': 'Compra Pendente',
    'strategy.statusInPosition': 'Em Posição',
    'strategy.statusSellPending': 'Venda Pendente',
    'strategy.statusCompleted': 'Concluída',
    'strategy.statusError': 'Erro',
    'strategy.paused': 'Pausada',
    'strategy.position': 'POSIÇÃO',
    'strategy.entryPrice': 'Preço de Entrada',
    'strategy.quantity': 'Quantidade',
    'strategy.currentPrice': 'Preço Atual',
    'strategy.unrealizedPnl': 'P&L Não Realizado',
    'strategy.realizedPnl': 'P&L Realizado',
    'strategy.totalTrades': 'Total Trades',
    'strategy.profitLoss': 'P&L',
    'strategy.winRate': 'Win Rate',
    'strategy.avgProfit': 'Lucro Médio',
    'strategy.totalFees': 'Total Taxas',
    'strategy.daysActive': 'Dias Ativo',
    'strategy.lastPrice': 'Último Preço',
    'strategy.lastChecked': 'Última Verificação',
    'strategy.checkInterval': 'Intervalo',
    'strategy.overview': 'Visão Geral',
    'strategy.signals': 'Sinais',
    'strategy.noSignals': 'Nenhum sinal',
    'strategy.triggerManual': '⚡ Executar',
    'strategy.execBuy': 'Compra',
    'strategy.execSell': 'Venda',
    'strategy.execDcaBuy': 'DCA Compra',
    'strategy.execGridBuy': 'Grid Compra',
    'strategy.execGridSell': 'Grid Venda',
    'strategy.execFailed': 'Falhou',
    
    // PNL (Profit and Loss)
    'pnl.title': '💰 PNL (24h)',
    'pnl.last24h': 'Último 24h',
    'pnl.previous': 'Anterior',
    'pnl.calculating': 'Calculando PNL...',
    'pnl.noData': 'Dados não disponíveis',
    'pnl.live': '● LIVE',
    'pnl.updating': 'Atualizando...',
    'pnl.24hLabel': 'últimas 24h',
    'pnl.24hShort': '24H',
    'pnl.24Hours': '24 Horas',
    'pnl.7Days': '7 Dias',
    'pnl.15Days': '15 Dias',
    'pnl.30Days': '30 Dias',
    'pnl.days': 'dias',
    'pnl.today': 'hoje',
    
    // Notifications
    'notifications.title': 'Notificações',
    'notifications.unread': 'não lidas',
    'notifications.unreadSingular': 'lida',
    'notifications.unreadPlural': 'lidas',
    'notifications.markAll': 'Marcar todas',
    'notifications.empty': 'Nenhuma notificação',
    'notifications.emptyMessage': 'Você está em dia! Não há notificações no momento.',
    'notifications.now': 'Agora',
    'notifications.minutesAgo': 'atrás',
    'notifications.hoursAgo': 'atrás',
    'notifications.yesterday': 'Ontem',
    'notifications.daysAgo': 'atrás',
    
    // Exchanges
    'exchanges.title': 'Corretoras',
    'exchanges.loading': 'Carregando exchanges...',
    'exchanges.hideZeroTokens': 'Ocultar saldo $0',
    'exchanges.hideZeroExchanges': 'Ocultar saldo $0',
    'exchanges.noExchanges': 'Nenhuma corretora vinculada',
    'exchanges.addFirstExchange': 'Adicione sua primeira corretora para começar a monitorar seus investimentos',
    'exchanges.allExchangesHidden': 'Todas as corretoras estão ocultas',
    'exchanges.disableFilterToSee': 'Desative o filtro para ver corretoras saldo zero',
    'exchanges.tokensAvailable': 'Tokens Disponíveis',
    'exchanges.asset': 'ativo',
    'exchanges.assets': 'ativos',
    'exchanges.error': 'Erro ao carregar corretoras',
    'exchanges.manage': 'Corretoras',
    'exchanges.connected': 'Conectadas',
    'exchanges.connectedSingular': 'conectada',
    'exchanges.connectedPlural': 'conectadas',
    'exchanges.available': 'Disponíveis',
    'exchanges.availableSingular': 'disponível',
    'exchanges.availablePlural': 'disponíveis',
    'exchanges.scanQR': 'Escanear QR Code',
    'exchanges.pasteFromClipboard': 'Colar da Área de Transferência',
    'exchanges.connect': 'Conectar',
    'exchanges.disconnect': 'Desconectar',
    'exchanges.delete': 'Deletar',
    'exchanges.viewAvailable': 'Ver Corretoras Disponíveis',
    'exchanges.connectModal': 'Conectar Corretora',
    'exchanges.addButton': '+ Adicionar',
    'exchanges.disconnectConfirm': 'Tem certeza que deseja desconectar a corretora',
    'exchanges.deleteConfirm': 'Tem certeza que deseja deletar permanentemente a corretora',
    'exchanges.deleteWarning': 'Esta ação não pode ser desfeita.',
    'exchanges.connectError': 'Não foi possível conectar a corretora',
    'exchanges.disconnectError': 'Não foi possível desconectar a corretora',
    'exchanges.deleteError': 'Não foi possível deletar a corretora',
    'exchanges.connectedAt': 'Conectada em',
    'exchanges.viewDetails': 'Ver Detalhes',
    'exchanges.active': 'ATIVA',
    'exchanges.inactive': 'INATIVA',
    'exchanges.alreadyConnected': 'Exchange já conectada',
    'exchanges.readyToConnect': 'Pronta para conectar',
    'exchanges.requiresPassphrase': 'Requer passphrase adicional',
    'exchanges.country': 'País de Origem',
    'exchanges.generalInfo': 'Informações Gerais',
    'exchanges.loadingDetails': 'Carregando detalhes...',
    'exchanges.exchangeId': 'Exchange ID',
    'exchanges.ccxtId': 'CCXT ID',
    'exchanges.lastUpdate': 'Última atualização',
    'exchanges.reconnectedAt': 'Reconectada em',
    'exchanges.disconnectedAt': 'Desconectada em',
    'exchanges.feeStructure': 'Estrutura de taxas disponível na exchange',
    'exchanges.name': 'Nome',
    'exchanges.website': 'Website',
    'exchanges.resources': '⚡ Recursos',
    'exchanges.availableMarkets': '📈 Mercados Disponíveis',
    'exchanges.tradingFees': 'Taxas de Trading',
    'exchanges.fundingFees': 'Taxas de Funding',
    'exchanges.maker': 'Maker',
    'exchanges.taker': 'Taker',
    'exchanges.deposit': 'Depósito',
    'exchanges.withdraw': 'Saque',
    // Deep link to exchange app
    'deposit.label': 'Abrir',
    'deposit.title': 'Abrir app da exchange',
    'deposit.confirmMessage': 'Você será redirecionado para o app da {exchange}. Nunca compartilhe suas credenciais e verifique sempre se está no app oficial.',
    'deposit.openApp': 'Continuar',
    'exchanges.confirmDelete': '⚠️ Confirmar Exclusão',
    'exchanges.confirmDisconnect': '⚠️ Confirmar Desconexão',
    'exchanges.qrSuccess': '✅ Sucesso!',
    'exchanges.qrLoaded': 'API Key e Secret carregados do QR Code!',
    'exchanges.qrFieldsLoaded': '{fields} carregados do QR Code!',
    'exchanges.qrFieldsExtracted': '{fields} extraídos do QR Code!',
    'exchanges.apiKey': 'API Key',
    'exchanges.apiSecret': 'API Secret',
    'exchanges.passphrase': 'Passphrase',
    'exchanges.enterApiKey': 'Digite sua API Key',
    'exchanges.enterApiSecret': 'Digite seu API Secret',
    'exchanges.enterPassphrase': 'Digite sua Passphrase',

    // Orders
    'orders.badge': 'Ordens',
    'orders.title': 'Abertas',
    'orders.empty': 'Nenhuma ordem aberta',
    'orders.emptyDescription': 'Você não possui ordens abertas em suas exchanges',
    'orders.emptyMessage': 'Você não possui ordens abertas nesta exchange',
    'orders.autoUpdate': 'Atualização automática a cada 5 min',
    'orders.lastSync': 'Última atualização',
    'orders.loading': 'Carregando ordens...',
    'orders.error': 'Erro ao carregar ordens',
    'orders.retry': 'Tentar novamente',
    'orders.noOrders': 'Sem ordens abertas',
    'orders.oneOrder': '1 ordem aberta',
    'orders.multipleOrders': 'ordens abertas',
    'orders.cancelAll': 'Cancelar Todas',
    'orders.cancelAllTitle': '⚠️ Cancelar Todas as Ordens',
    'orders.cancelAllMessage': 'Deseja realmente cancelar TODAS as {count} ordem(ns) abertas nesta exchange?',
    'orders.cancelAllWarning': '⚠️ Esta ação não pode ser desfeita!',
    'orders.cancelAllNo': 'Não',
    'orders.cancelAllYes': 'Sim, Cancelar Todas',
    'orders.cancel': 'Cancelar',
    'orders.cancelling': 'Cancelando...',
    'orders.viewDetails': 'Ver Detalhes',
    'orders.clone': 'Clonar',
    'orders.cloneTitle': 'Clonar Ordem',
    'orders.cloneMessage': 'Deseja criar uma nova ordem idêntica a esta?',
    'orders.cloneTooltip': 'Clonar ordem',
    'orders.confirmClone': 'Sim, Clonar',
    'orders.insufficientBalance': 'Saldo insuficiente para esta ordem',
    'orders.loadingOrders': 'Carregando ordens...',

    // Alerts Modal
    'alerts.createTitle': '🔔 Criar Novo Alerta',
    'alerts.editTitle': '✏️ Editar Alerta',
    'alerts.description': 'Configure um alerta personalizado para ser notificado quando um token atingir determinada variação ou preço.',
    'alerts.tokenLabel': 'Token (Símbolo) *',
    'alerts.tokenPlaceholder': 'Ex: BTC, ETH, USDT',
    'alerts.exchangeLabel': 'Exchange (opcional)',
    'alerts.exchangePlaceholder': 'Deixe vazio para todas exchanges',
    'alerts.exchangeHelper': 'Se deixar vazio, o alerta funcionará em todas as exchanges',
    'alerts.typeLabel': 'Tipo de Alerta',
    'alerts.typePercentage': '📊 Variação Percentual (24h)',
    'alerts.typePrice': '💰 Preço Absoluto',
    'alerts.conditionLabel': 'Condição',
    'alerts.conditionAbove': '📈 Acima de (maior ou igual)',
    'alerts.conditionBelow': '📉 Abaixo de (menor ou igual)',
    'alerts.valueLabel': 'Valor *',
    'alerts.valuePercentage': '(%)',
    'alerts.valuePrice': '($)',
    'alerts.valuePlaceholderPercentage': 'Ex: -5 (para queda de 5%)',
    'alerts.valuePlaceholderPrice': 'Ex: 50000 (para $50,000)',
    'alerts.valueHelperPercentage': 'Use valores negativos para quedas (ex: -10) e positivos para altas (ex: +10)',
    'alerts.valueHelperPrice': 'Informe o preço em dólares (USD)',
    'alerts.previewLabel': '📋 Preview do Alerta:',
    'alerts.previewText': 'Você será notificado quando',
    'alerts.previewOn': 'na',
    'alerts.previewWillBe': 'estiver',
    'alerts.previewAbove': 'acima de',
    'alerts.previewBelow': 'abaixo de',
    'alerts.previewVariation': 'de variação',
    'alerts.cancel': 'Cancelar',
    'alerts.create': 'Criar Alerta',
    'alerts.update': 'Atualizar',
    'alerts.saving': 'Salvando...',
    
    // Token Monitor Notifications
    'tokenMonitor.falling': '{symbol} em Queda',
    'tokenMonitor.fallingMessage': '{symbol} caiu {percent}% nas últimas 24h. Preço: ${price}',
    'tokenMonitor.rising': '🚀 {symbol} em Alta',
    'tokenMonitor.risingMessage': '{symbol} subiu {percent}% nas últimas 24h! Preço: ${price}',
    'tokenMonitor.rapidChange': '⚡ {symbol} - Mudança Rápida',
    'tokenMonitor.rapidChangeMessage': '{symbol} {direction} rapidamente. Variação: {variation}%. Preço: ${price}',
    'tokenMonitor.rose': 'subiu',
    'tokenMonitor.fell': 'caiu',
    'tokenMonitor.below': '📉 {symbol} Abaixo de {value}%',
    'tokenMonitor.belowMessage': '{symbol} caiu para {current}% (limite: {value}%). Preço: ${price}',
    'tokenMonitor.above': '📈 {symbol} Acima de {value}%',
    'tokenMonitor.aboveMessage': '{symbol} subiu para {current}% (limite: {value}%). Preço: ${price}',
    'tokenMonitor.priceBelowTitle': '💰 {symbol} Abaixo de ${value}',
    'tokenMonitor.priceBelowMessage': '{symbol} atingiu ${current} (limite: ${value}). Variação: {variation}%',
    'tokenMonitor.priceAboveTitle': '💰 {symbol} Acima de ${value}',
    'tokenMonitor.priceAboveMessage': '{symbol} atingiu ${current} (limite: ${value}). Variação: {variation}%',
    
    'orders.order': 'ordem',
    'orders.ordersPlural': 'ordens',
    'orders.timeAgo.minutes': '{minutes}m atrás',
    'orders.timeAgo.hours': '{hours}h atrás',
    'orders.timeAgo.days': '{days}d atrás',
    'orders.edit': 'Editar',
    'orders.editTitle': 'Editar Ordem',
    'orders.newPrice': 'Novo Preço',
    'orders.newAmount': 'Nova Quantidade',
    'orders.save': 'Salvar',
    'orders.editSuccess': 'Ordem editada com sucesso!',
    'orders.editError': 'Erro ao editar ordem',
    'orders.price': 'Preço',
    'orders.amount': 'Quantidade',
    'orders.filled': 'Executado',
    'orders.total': 'Total',
    'orders.type.limit': 'LIMIT',
    'orders.type.market': 'MARKET',
    'orders.type.stopLoss': 'STOP LOSS',
    'orders.side.buy': 'COMPRA',
    'orders.side.sell': 'VENDA',
    'orders.details.status': 'Status',
    'orders.details.progress': 'Progresso de Execução',
    'orders.details.executed': 'executado',
    'orders.details.remaining': 'Restante',
    'orders.details.title': 'Detalhes da Ordem',
    'orders.details.orderId': 'ID da Ordem',
    'orders.details.totalCost': 'Custo Total',
    'orders.details.dateTime': 'Data/Hora',
    'orders.details.fee': 'Taxa',
    'orders.details.trades': 'Trades Executados',
    'orders.details.trade': 'Trade',
    'orders.details.close': 'Fechar',
    'orders.count': 'ordens',
    'orders.countSingular': 'ordem',
    'orders.confirmCancel': 'Confirmar Cancelamento',
    'orders.cancelingOrder': 'Cancelando ordem...',
    'orders.confirmCancelMessage': 'Tem certeza que deseja cancelar esta ordem?',
    'orders.pair': 'Par',
    'orders.type': 'Tipo',
    'orders.exchange': 'Exchange',
    'orders.quantity': 'Quantidade',
    'orders.cancelingAllOrders': 'Cancelando todas as ordens...',
    'orders.cancelFailed': 'Não foi possível cancelar',
    'orders.errorCode': 'Código',
    'orders.cancelOrder': 'Cancelar Ordem',
    'orders.errorDetails': 'Detalhes do Erro',
    'orders.fullResponse': 'Resposta completa:',
    'orders.cancelConfirm': 'Deseja realmente cancelar esta ordem {side}?',
    'orders.cancelBuy': 'de compra',
    'orders.cancelSell': 'de venda',
    'orders.cancelOrderError': 'Erro ao cancelar ordem',
    'orders.unknownCancelError': 'Erro desconhecido ao cancelar ordem',
    'orders.timeoutError': 'Timeout: A exchange não respondeu a tempo',
    'orders.networkError': 'Erro de rede: Verifique sua conexão',
    'orders.message': 'Mensagem:',
    'orders.code': 'Código:',
    
    // Trade
    'trade.tooltip': 'Negociar',
    'trade.title': 'Trade',
    'trade.buy': 'Comprar',
    'trade.sell': 'Vender',
    'trade.creatingOrder': 'Criando ordem...',
    'trade.confirmBuy': 'Deseja realmente comprar',
    'trade.confirmSell': 'Deseja realmente vender',
    
    // Exchanges tooltips and misc
    // 'exchanges.requiresPassphrase' movido para cima (linha 170)
    
    'exchanges.status': 'Status',
    'exchanges.activate': 'Ativar',
    'exchanges.hidden': 'ocultas',
    'exchanges.moreAssets': 'mais',
    'exchanges.deactivate': 'Desativar',
    'exchanges.activateConfirm': 'Tem certeza que deseja ativar a corretora',
    'exchanges.deactivateConfirm': 'Tem certeza que deseja desativar a corretora',
    'exchanges.activateWarning': 'Ela ficará disponível para uso nas estratégias.',
    'exchanges.deactivateWarning': 'Ela não será mais utilizada pelas estratégias.',
    
    // Token Details
    'token.details': 'Detalhes do Token',
    'token.currentPrice': 'Preço Atual',
    'token.priceVariation': 'Variação de Preço',
    'token.high24h': 'Máxima 24h',
    'token.low24h': 'Mínima 24h',
    'token.volume24h': 'Volume 24h',
    'token.marketInfo': 'Informações de Mercado',
    'token.market': 'Mercado',
    'token.limits': 'Limites',
    'token.minAmount': 'Qtd. Mínima',
    'token.maxAmount': 'Qtd. Máxima',
    'token.minCost': 'Custo Mín.',
    'token.maxCost': 'Custo Máx.',
    'token.precision': 'Precisão',
    'token.amountPrecision': 'Qtd.',
    'token.pricePrecision': 'Preço',
    'token.bidPrice': 'Preço de Compra',
    'token.askPrice': 'Preço de Venda',
    'token.spread': 'Spread',
    'token.lastUpdate': 'Última atualização',
    'token.pair': 'Par',
    'token.noData': 'Dados não disponíveis',
    'token.loadingVariations': 'Carregando variações...',
    'token.tokensIn': 'Tokens em',
    'token.totalIn': 'Total em',
    'token.exchanges': 'Corretoras',
    'token.amount': 'Quantidade:',
    'token.price': 'Preço:',
    'token.total': 'Total:',
    'token.value': 'Valor:',
    'token.viewDetails': 'Ver Detalhes',
    'token.trade': 'Negociar',
    'token.noBalance': 'Nenhum token com saldo disponível',
    
    // Search
    'search.tokens': 'Pesquisar Tokens',
    'search.placeholder': 'Digite o símbolo ou nome do token...',
    'search.noResults': 'Nenhum token encontrado',
    'search.startTyping': 'Digite para pesquisar seus tokens',
    
    // Common
    'common.close': 'Fechar',
    'common.cancel': 'Cancelar',
    'common.back': 'Voltar',
    'common.save': 'Salvar',
    'common.continue': 'Continuar',
    'common.confirm': 'Confirmar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.refresh': 'Atualizar',
    'common.tryAgain': 'Tentar Novamente',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.warning': 'Aviso',
    'common.attention': 'Atenção',
    'common.ok': 'OK',
    'common.next': 'Próximo',
    'common.create': 'Criar',
    'common.viewDetails': 'Ver Detalhes',
    'common.updatingData': 'Atualizando dados...',
    'common.loadingTokens': 'Carregando tokens...',
    'common.updated': 'Atualizado:',
    'common.updatedAt': 'Atualizado às {time}',
    'common.search': 'Buscar',
    'common.noResults': 'Nenhum resultado',
    'common.delete': 'Excluir',
    'common.remove': 'Remover',
    'common.retry': 'Tentar novamente',
    'common.showMore': 'Ver mais',
    'common.showLess': 'Ver menos',
    
    // Error Messages
    'error.cameraAccess': 'Não foi possível acessar a câmera',
    'error.loadExchanges': 'Não foi possível carregar suas exchanges',
    'error.loadTokens': 'Não foi possível carregar os tokens',
    'error.createStrategy': 'Não foi possível criar a estratégia',
    'error.connectExchange': 'Não foi possível conectar a exchange',
    'error.updateExchangeStatus': 'Não foi possível atualizar o status da exchange',
    'error.disconnectExchange': 'Não foi possível desconectar a exchange',
    'error.deleteExchange': 'Não foi possível deletar a exchange',
    'error.pasteClipboard': 'Não foi possível colar da área de transferência',
    'error.fillAllFields': 'Por favor, preencha todos os campos',
    'error.fillApiKeys': 'Por favor, preencha API Key e API Secret',
    'error.passphraseRequired': 'Esta exchange requer uma Passphrase',
    'error.loginFailed': 'Falha ao fazer login',
    'error.biometricFailed': 'Falha na autenticação biométrica',
    'error.unknownError': 'Erro desconhecido',
    'error.invalidResponse': 'Formato de resposta inválido',
    
    // Success Messages
    'success.strategyCreated': 'Estratégia criada com sucesso!',
    'success.pastedClipboard': 'Colado!',
    'success.textPasted': 'Texto colado da área de transferência',
    
    // Warning Messages
    'warning.noTokensAvailable': 'Esta exchange não possui tokens disponíveis',
    'warning.emptyClipboard': 'Área vazia',
    'warning.noClipboardText': 'Não há texto na área de transferência',
    
    // Exchange Alerts
    'alert.exchangeInactive': 'Exchange Inativa',
    
    // Auth (OAuth)
    'auth.completingLogin': 'Concluindo login...',
    
    // Maintenance Screen
    'maintenance.title': 'Estamos em Manutenção',
    'maintenance.message': 'Nossos servidores estão temporariamente indisponíveis. Estamos trabalhando para restaurar o serviço o mais rápido possível.',
    'maintenance.subMessage': 'Pedimos desculpas pelo inconveniente. Tente novamente em alguns instantes.',
    'maintenance.retry': 'Tentar Novamente',
    'maintenance.contact': 'Se o problema persistir, entre em contato com o suporte.',
    
    // Login Screen
    'login.welcome': 'Bem vindo!',
    'login.subtitle': 'Acesse sua conta para continuar',
    'login.email': 'Email',
    'login.emailPlaceholder': 'seu@email.com',
    'login.password': 'Senha',
    'login.passwordPlaceholder': '••••••••',
    'login.showPassword': 'Mostrar',
    'login.hidePassword': 'Ocultar',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.signIn': 'Entrar',
    'login.orContinueWith': 'ou continue com',
    'login.or': 'ou',
    'login.signInWith': 'Entrar com',
    'login.google': 'Google',
    'login.apple': 'Apple',
    'login.noAccount': 'Não tem uma conta?',
    'login.signUp': 'Cadastre-se',
    'login.googleError': 'Falha ao fazer login com Google',
    'login.appleError': 'Falha ao fazer login com Apple',
    
    // SignUp Screen
    'signup.fillAllFields': 'Por favor, preencha todos os campos',
    'signup.passwordMismatch': 'As senhas não coincidem',
    'signup.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'signup.accountCreated': 'Conta criada com sucesso!',
    'signup.createAccountFailed': 'Falha ao criar conta',
    'signup.googleSignupFailed': 'Falha ao cadastrar com Google',
    'signup.appleSignupFailed': 'Falha ao cadastrar com Apple',
    'signup.title': 'Criar Conta',
    'signup.subtitle': 'Comece sua jornada hoje',
    'signup.nameLabel': 'Nome completo',
    'signup.namePlaceholder': 'João Silva',
    'signup.emailLabel': 'Email',
    'signup.emailPlaceholder': 'seu@email.com',
    'signup.passwordLabel': 'Senha',
    'signup.passwordPlaceholder': 'Mínimo 6 caracteres',
    'signup.confirmPasswordLabel': 'Confirmar senha',
    'signup.confirmPasswordPlaceholder': 'Digite a senha novamente',
    'signup.showPassword': 'Mostrar',
    'signup.hidePassword': 'Ocultar',
    'signup.termsText': 'Ao criar uma conta, você concorda com nossos',
    'signup.termsOfService': 'Termos de Serviço',
    'signup.and': 'e',
    'signup.privacyPolicy': 'Política de Privacidade',
    'signup.createButton': 'Criar Conta',
    'signup.orSignUpWith': 'ou cadastre-se com',
    'signup.google': 'Google',
    'signup.apple': 'Apple',
    'signup.alreadyHaveAccount': 'Já tem uma conta?',
    'signup.signIn': 'Entrar',
    
    // Portfolio & Home Additional
    'portfolio.basedOnBalance': 'Patrimônio baseado no saldo das corretoras',
    'portfolio.updatedAt': 'Atualizado em',
    'portfolio.variationsNote': 'As variações são consultadas nas corretoras',
    'portfolio.lastDays': 'Últimos {days} dias',
    'portfolio.dailyPnl': 'PNL DIÁRIO (HOJE)',
    'portfolio.today': 'HOJE',
    'portfolio.yesterday': 'Ontem',
    'portfolio.noPnlData': 'Dados indisponíveis',
    'portfolio.evolution': 'Evolução de {days} dias',
    'portfolio.noEvolutionData': 'Sem dados de evolução',
    'portfolio.day': 'dia',
    'portfolio.days': 'dias',
    
    // Settings Additional
    'settings.securityPrivacySection': 'Segurança e Privacidade',
    'settings.infoSectionTitle': 'Informações',
    'settings.accountSection': 'Conta',
    'settings.deleteAccount': 'Excluir Conta',
    'settings.biometricDisabled': 'desativado com sucesso',
    // Removed duplicate 'settings.biometricEnabled'
    'settings.biometricError': 'Falha ao configurar biometria',
    'settings.deleteAccountTitle': '⚠️ Confirmar Exclusão',
    'settings.deleteAccountWarning': 'ATENÇÃO: Esta ação é IRREVERSÍVEL!\n\nTem certeza absoluta que deseja excluir sua conta?',
    'settings.deleteAccountConfirm': 'ATENÇÃO: Esta ação é IRREVERSÍVEL!\n\nDigite "EXCLUIR" para confirmar a exclusão da conta:',
    'settings.deleteAccountSuccess': 'Conta excluída com sucesso',
    'settings.deleteAccountButton': 'Excluir',
    'settings.cancel': 'Cancelar',
    
    // Profile
    'profile.logoutError': 'Não foi possível realizar o logout',

    // Trade (extras)
    'trade.confirmOrder': 'Confirmar Ordem',
    'trade.pair': 'Par',
    'trade.side': 'Lado',
    'trade.type': 'Tipo',
    'trade.price': 'Preço',
    'trade.quantity': 'Quantidade',
    'trade.totalToPay': 'Total a Pagar',
    'trade.totalToReceive': 'Total a Receber',
    'trade.createStrategy': 'Criar Estratégia',

    // Watchlist
    'watchlist.noFavorites': 'Nenhum favorito ainda',
    'watchlist.noFavoritesDesc': 'Marque tokens como favoritos clicando na estrela (⭐) na lista de assets',
    'watchlist.noBalance': 'Sem saldo',
    'watchlist.price': 'Preço',
    'watchlist.totalValue': 'Valor Total',
    'watchlist.viewDetails': 'Ver Detalhes',
    'watchlist.trade': 'Negociar',
    'watchlist.favoriteNoBalance': 'Favorito sem saldo',
    'watchlist.awaitingPrice': 'Token aguardando consulta de preço',
    'watchlist.status': 'Status',
    'watchlist.info': 'Info',

    // Alerts (simplificados)
    'alerts.title': 'Alertas',
    'alerts.createAlert': 'Criar Alerta de Preço',
    'alerts.alertType': 'Tipo de Alerta',
    'alerts.absolutePrice': 'Preço Absoluto',
    'alerts.percentage': 'Porcentagem',
    'alerts.condition': 'Condição',
    'alerts.above': 'Acima de',
    'alerts.below': 'Abaixo de',
    'alerts.crossesUp': 'Cruza acima',
    'alerts.crossesDown': 'Cruza abaixo',
    'alerts.targetPrice': 'Preço Alvo',
    'alerts.percentageLabel': 'Porcentagem',
    'alerts.frequency': 'Frequência',
    'alerts.once': 'Uma vez',
    'alerts.always': 'Sempre',
    'alerts.daily': 'Diário',
    'alerts.customMessage': 'Mensagem Personalizada',
    'alerts.previewAlert': 'Preview do Alerta:',
    'alerts.frequencyLabel': 'Frequência:',
    'alerts.createButton': 'Criar Alerta',
    'alerts.noAlerts': 'Nenhum alerta configurado',
    'alerts.noAlertsDesc': 'Crie seu primeiro alerta de preço para receber notificações',
    'alerts.loadingAlerts': 'Carregando alertas...',
    'alerts.removeAlert': 'Remover Alerta',
    'alerts.triggered': 'Disparado',
    'alerts.currentPrice': 'Preço atual:',

    // Notifications (extras)
    'notifications.clearAll': 'Limpar Notificações',
    'notifications.clearAllConfirm': 'Tem certeza que deseja remover todas as {count} notificações?',
    'notifications.clearAllButton': 'Limpar Todas',
    'notifications.desc': 'Notificações e avisos',

    // Strategy (extras)
    'strategy.newTemplate': 'Criar Novo Template',
    'strategy.customTemplate': 'Personalize seu próprio template',
    'strategy.noExchanges': 'Nenhuma exchange conectada',
    'strategy.connectExchange': 'Conecte uma exchange na aba "Exchanges"',
    'strategy.tapToChange': 'Toque para alterar',
    'strategy.summary': 'Resumo da Estratégia',
    'strategy.connected': 'Conectada',
    'strategy.protectionEnabled': 'Proteção ativada',
    'strategy.searchToken': 'Buscar token (ex: BTC, ETH, SOL...)',
    'strategy.results': '{count} resultado{plural}',
    'strategy.tokensAvailable': '{count} tokens disponíveis',
    'strategy.noTokenFound': 'Nenhum token encontrado para "{query}"',
    'strategy.noTokenAvailable': 'Nenhum token disponível',

    // Market
    'market.currentPrice': 'Preço Atual',
    'market.change24h': 'Variação 24h',
    'market.chartUnavailable': 'Gráfico não disponível',
    'market.apiTemporary': 'Pode ser um problema temporário da API',

    // Assets
    'assets.availableOn': 'Disponível na {exchange}',
    'assets.searchingExchanges': 'Buscando {query} nas exchanges...',
    'assets.tokenNotFound': 'Token {symbol} não encontrado',
    'assets.tokenNotFoundDesc': 'Não foi possível localizar este token nas exchanges conectadas ou APIs externas.',
    'assets.noTokenInExchange': 'Nenhum token nesta exchange',

    // Token Details
    'tokenDetails.totalQuantity': 'Quantidade Total',
    'tokenDetails.totalValueUsd': 'Valor Total (USD)',

    // Pie Chart
    'chart.error': '⚠️ Erro',
    'chart.fetchError': 'Falha ao buscar saldo',

    // Profile Menu
    'profileMenu.alerts': 'Alertas',
    'profileMenu.settings': 'Configurações',
    'profileMenu.settingsDesc': 'Preferências e conta',

    // Icon Selector
    'iconSelector.title': 'Selecionar Ícone',

    // QR Scanner
    'qr.requestingPermission': 'Solicitando permissão da câmera...',
    'qr.noAccess': 'Sem acesso à câmera',
    'qr.noAccessDesc': 'Para escanear QR codes, você precisa permitir o acesso à câmera nas configurações do dispositivo.',

    // GenericItemList
    'genericList.noTokenInExchange': 'Nenhum token nesta exchange',
    'genericList.item': 'item',
    'genericList.items': 'itens',
  },
  'en-US': {
    // Navigation
    'nav.home': 'Home',
    'nav.exchanges': 'Exchanges',
    'nav.strategies': 'Strategies',
    'nav.profile': 'Profile',
    
    // Home Screen
    'home.title': 'CryptoHub',
    'home.subtitle': 'Unified tokens',
    'home.portfolio': 'Total Portfolio',
    'home.last24h': 'last 24h',
    'home.performance': 'Performance',
    'home.exchanges': 'My Exchanges',
    'home.noData': 'No data available',
    'home.loading': 'Loading data...',
    'home.distribution': 'By Exchange',
    'home.exchangeBalances': 'Balances by Exchange',
    'home.exchangeDetails': 'Details by exchange',
    'home.exchangeHide': 'Hide details',
    'home.noExchangesConnected': 'No exchanges connected',
    'home.tabSummary': 'Summary',
    'home.tabAssets': 'Assets',
    'home.tabOrders': 'Orders',
    'home.updating': 'Updating...',
    
    // Top Gainers/Losers
    'topGainersLosers.gainersTitle': 'Top Gainers (24h)',
    'topGainersLosers.losersTitle': 'Top Losers (24h)',
    'topGainersLosers.noGainers': 'No significant gains',
    'topGainersLosers.noLosers': 'No significant losses',
    'topGainersLosers.viewAll': 'View all',
    'topGainersLosers.allGainersTitle': 'All Gainers (24h)',
    'topGainersLosers.allLosersTitle': 'All Losers (24h)',
    'topGainersLosers.total': 'Total',
    'topGainersLosers.tokens': 'tokens',
    
    // Profile Screen
    'profile.title': 'Profile',
    'profile.subtitle': 'Your account',
    'profile.user': 'CryptoHub User',
    'profile.memberSince': 'Member since',
    'profile.settings': 'Settings',
    'profile.notifications': 'Notifications',
    'profile.security': 'Security',
    'profile.language': 'Language',
    'profile.languagePt': 'Português (BR)',
    'profile.languageEn': 'English (US)',
    'profile.currency': 'Preferred Currency',
    'profile.appearance': 'Appearance',
    'profile.darkMode': 'Dark Mode',
    'profile.enabled': 'Enabled',
    'profile.disabled': 'Disabled',
    'profile.about': 'About',
    'profile.aboutApp': 'About the App',
    'profile.terms': 'Terms of Use',
    'profile.privacy': 'Privacy',
    'profile.logout': 'Sign Out',
    'profile.logoutConfirm': 'Are you sure you want to logout?',
    'profile.version': 'Version',
    'profile.termsOfUse': 'Terms of Use',
    'profile.privacyPolicy': 'Privacy Policy',
    'profile.edit': 'Edit',
    'profile.personalInfo': 'PERSONAL INFORMATION',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.actions': 'ACTIONS',
    'profile.changePassword': 'Change Password',
    'profile.exportData': 'Export Data',
    
    // Settings Screen
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your app',
    'settings.systemTitle': 'System',
    'settings.appearance': 'Appearance',
    'settings.notificationsSection': 'Notifications',
    'settings.securitySection': 'Security & Privacy',
    'settings.infoSection': 'Information',
    'settings.securityModal': 'Security',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.twoFactorSms': '2FA via SMS',
    'settings.twoFactorSmsDesc': 'Receive verification codes via SMS',
    'settings.googleAuth': 'Google Authenticator',
    'settings.googleAuthDesc': 'Use the Google Authenticator app',
    'settings.autoLock': 'Auto Lock',
    'settings.autoLockEnable': 'Enable Lock',
    'settings.autoLockDesc': 'Lock app after inactivity',
    'settings.inactivityTime': 'Inactivity Time',
    'settings.alerts': 'Alerts',
    'settings.loginAlerts': 'Login Alerts',
    'settings.loginAlertsDesc': 'Notify about new logins',
    'settings.activated': 'Enabled',
    'settings.deactivated': 'Disabled',
    'settings.biometricEnabled': 'enabled successfully',
    'settings.biometricDisabled': 'disabled successfully',
    'settings.biometricError': 'Failed to configure biometrics',
    
    // Strategy Screen
    'strategy.title': 'Strategies',
    'strategy.new': '+ New',
    'strategy.strategies': 'strategies',
    'strategy.strategy': 'strategy',
    'strategy.executions': 'Executions',
    'strategy.execution': 'execution',
    'strategy.empty': 'No strategies created',
    'strategy.emptyDesc': 'Create your first automated strategy',
    'strategy.executionsEmpty': 'No executions recorded',
    'strategy.executionsEmptyDesc': 'Your strategy executions will appear here',
    'strategy.noExecutions': 'No executions',
    'strategy.executionsWillAppear': 'Executed orders will appear here',
    'strategy.active': 'Active',
    'strategy.inactive': 'Inactive',
    'strategy.viewDetails': 'View Details',
    'strategy.activate': 'Activate',
    'strategy.deactivate': 'Deactivate',
    'strategy.delete': 'Delete',
    'strategy.confirmDelete': 'Are you sure you want to delete this strategy?',
    'strategy.deleteWarning': 'This action cannot be undone.',
    'strategy.activateConfirm': 'Do you want to activate this strategy?',
    'strategy.deactivateConfirm': 'Do you want to deactivate this strategy?',
    'strategy.statusWillChange': 'The strategy status will be changed.',
    'strategy.simple': 'Simple',
    'strategy.simpleDesc': 'Basic strategy (1 TP 5%, SL 2%)',
    'strategy.conservative': 'Conservative',
    'strategy.conservativeDesc': 'Maximum protection (2 TPs, trailing stop)',
    'strategy.aggressive': 'Aggressive',
    'strategy.aggressiveDesc': 'Maximum profit (3 TPs, active DCA)',
    'strategy.templates': 'Templates',
    'strategy.templatesSubtitle': 'Standard strategy',
    'strategy.createNew': 'Create New Strategy',
    'strategy.riskLevel': 'Risk',
    'strategy.configs': 'Configuration',
    'strategy.newStrategy': 'New Strategy',
    'strategy.selectTemplate': 'Select a pre-configured strategy',
    'strategy.selectExchange': 'Select the exchange',
    'strategy.selectToken': 'Select the token',
    'strategy.step': 'Step',
    'strategy.of': 'of',
    'strategy.chooseTemplate': 'Choose a template',
    'strategy.chooseExchange': 'Choose the exchange',
    'strategy.chooseToken': 'Choose the token',
    'strategy.labelTemplate': 'Template',
    'strategy.labelExchange': 'Exchange',
    'strategy.labelToken': 'Token',
    'strategy.selectExchangeDesc': 'Choose where the strategy will be executed',
    'strategy.selectTokenDesc': 'Choose the token for trading',
    'strategy.details': 'Strategy Details',
    'strategy.notFound': 'Strategy not found',
    'strategy.errorLoading': 'Error loading strategy',
    'strategy.name': 'STRATEGY',
    'strategy.configuration': 'CONFIGURATION',
    'strategy.exchange': 'Exchange',
    'strategy.tradingPair': 'Trading Pair',
    'strategy.template': 'Template',
    'strategy.token': 'Token',
    'strategy.totalExecutions': 'Executions',
    'strategy.nextCheck': 'Next Check',
    'strategy.reason': 'Reason',
    'strategy.buy': 'Buy',
    'strategy.sell': 'Sell',
    'strategy.soon': 'Soon...',
    'strategy.now': 'Now',
    'strategy.inOneMinute': 'In 1 minute',
    'strategy.in': 'In',
    'strategy.minutes': 'minutes',
    'strategy.takeProfit': 'TAKE PROFIT',
    'strategy.stopLoss': 'STOP LOSS',
    'strategy.information': 'INFORMATION',
    'strategy.level': 'Level',
    'strategy.ofPosition': 'of position',
    'strategy.whenReaches': 'When reaches',
    'strategy.stopAt': 'Stop at',
    'strategy.toLimitLosses': 'to limit losses',
    'strategy.createdAt': 'Created at',
    'strategy.lastUpdate': 'Last update',
    'strategy.status': 'Status',
    'strategy.statusIdle': 'Idle',
    'strategy.statusMonitoring': 'Monitoring',
    'strategy.statusBuyPending': 'Buy Pending',
    'strategy.statusInPosition': 'In Position',
    'strategy.statusSellPending': 'Sell Pending',
    'strategy.statusCompleted': 'Completed',
    'strategy.statusError': 'Error',
    'strategy.paused': 'Paused',
    'strategy.position': 'POSITION',
    'strategy.entryPrice': 'Entry Price',
    'strategy.quantity': 'Quantity',
    'strategy.currentPrice': 'Current Price',
    'strategy.unrealizedPnl': 'Unrealized P&L',
    'strategy.realizedPnl': 'Realized P&L',
    'strategy.totalTrades': 'Total Trades',
    'strategy.profitLoss': 'P&L',
    'strategy.winRate': 'Win Rate',
    'strategy.avgProfit': 'Avg Profit',
    'strategy.totalFees': 'Total Fees',
    'strategy.daysActive': 'Days Active',
    'strategy.lastPrice': 'Last Price',
    'strategy.lastChecked': 'Last Checked',
    'strategy.checkInterval': 'Check Interval',
    'strategy.overview': 'Overview',
    'strategy.signals': 'Signals',
    'strategy.noSignals': 'No signals yet',
    'strategy.triggerManual': '⚡ Tick',
    'strategy.execBuy': 'Buy',
    'strategy.execSell': 'Sell',
    'strategy.execDcaBuy': 'DCA Buy',
    'strategy.execGridBuy': 'Grid Buy',
    'strategy.execGridSell': 'Grid Sell',
    'strategy.execFailed': 'Failed',
    
    // PNL (Profit and Loss)
    'pnl.title': '💰 PNL (24h)',
    'pnl.currentBalance': 'Current Balance',
    'pnl.last24h': 'Last 24h',
    'pnl.previous': 'Previous',
    'pnl.calculating': 'Calculating PNL...',
    'pnl.noData': 'Data not available',
    'pnl.live': '● LIVE',
    'pnl.updating': 'Updating...',
    'pnl.24hLabel': 'last 24h',
    'pnl.24hShort': '24H',
    'pnl.24Hours': '24 Hours',
    'pnl.7Days': '7 Days',
    'pnl.15Days': '15 Days',
    'pnl.30Days': '30 Days',
    'pnl.days': 'days',
    'pnl.today': 'today',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread',
    'notifications.unreadSingular': 'read',
    'notifications.unreadPlural': 'read',
    'notifications.markAll': 'Mark all',
    'notifications.empty': 'No notifications',
    'notifications.emptyMessage': 'You\'re all caught up! No notifications at this time.',
    'notifications.now': 'Now',
    'notifications.minutesAgo': 'ago',
    'notifications.hoursAgo': 'ago',
    'notifications.yesterday': 'Yesterday',
    'notifications.daysAgo': 'ago',
    
    // Exchanges
    'exchanges.title': 'Exchanges',
    'exchanges.loading': 'Loading exchanges...',
    'exchanges.hideZero': 'Hide exchanges $0 balance',
    'exchanges.hideZeroTokens': 'Hide tokens $0 balance',
    'exchanges.hideZeroExchanges': 'Hide exchanges $0 balance',
    'exchanges.noExchanges': 'No exchanges linked',
    'exchanges.addFirstExchange': 'Add your first exchange to start monitoring your investments',
    'exchanges.allExchangesHidden': 'All exchanges are hidden',
    'exchanges.disableFilterToSee': 'Disable the filter to see exchanges with zero balance',
    'exchanges.tokensAvailable': 'Available Tokens',
    'exchanges.asset': 'asset',
    'exchanges.assets': 'assets',
    'exchanges.error': 'Error loading exchanges',
    'exchanges.manage': 'Exchanges',
    'exchanges.connected': 'Connected',
    'exchanges.connectedSingular': 'connected',
    'exchanges.connectedPlural': 'connected',
    'exchanges.available': 'Available',
    'exchanges.availableSingular': 'available',
    'exchanges.availablePlural': 'available',
    'exchanges.scanQR': 'Scan QR Code',
    'exchanges.pasteFromClipboard': 'Paste from Clipboard',
    'exchanges.connect': 'Connect',
    'exchanges.disconnect': 'Disconnect',
    'exchanges.delete': 'Delete',
    'exchanges.viewAvailable': 'View Available Exchanges',
    'exchanges.connectModal': 'Connect Exchange',
    'exchanges.addButton': '+ Add',
    'exchanges.disconnectConfirm': 'Are you sure you want to disconnect the exchange',
    'exchanges.deleteConfirm': 'Are you sure you want to permanently delete the exchange',
    'exchanges.deleteWarning': 'This action cannot be undone.',
    'exchanges.connectError': 'Could not connect the exchange',
    'exchanges.disconnectError': 'Could not disconnect the exchange',
    'exchanges.deleteError': 'Could not delete the exchange',
    'exchanges.connectedAt': 'Connected at',
    'exchanges.viewDetails': 'View Details',
    'exchanges.active': 'ACTIVE',
    'exchanges.inactive': 'INACTIVE',
    'exchanges.alreadyConnected': 'Exchange already connected',
    'exchanges.readyToConnect': 'Ready to connect',
    'exchanges.requiresPassphrase': 'Requires additional passphrase',
    'exchanges.status': 'Status',
    'exchanges.activate': 'Activate',
    'exchanges.hidden': 'hidden',
    'exchanges.moreAssets': 'more',
    'exchanges.deactivate': 'Deactivate',
    'exchanges.activateConfirm': 'Are you sure you want to activate the exchange',
    'exchanges.deactivateConfirm': 'Are you sure you want to deactivate the exchange',
    'exchanges.activateWarning': 'It will be available for use in strategies.',
    'exchanges.deactivateWarning': 'It will no longer be used by strategies.',
    'exchanges.country': 'Country',
    'exchanges.generalInfo': 'General Information',
    'exchanges.loadingDetails': 'Loading details...',
    'exchanges.exchangeId': 'Exchange ID',
    'exchanges.ccxtId': 'CCXT ID',
    'exchanges.lastUpdate': 'Last update',
    'exchanges.reconnectedAt': 'Reconnected at',
    'exchanges.disconnectedAt': 'Disconnected at',
    'exchanges.feeStructure': 'Fee structure available on the exchange',
    'exchanges.name': 'Name',
    'exchanges.website': 'Website',
    'exchanges.resources': '⚡ Resources',
    'exchanges.availableMarkets': '📈 Available Markets',
    'exchanges.tradingFees': 'Trading Fees',
    'exchanges.fundingFees': 'Funding Fees',
    'exchanges.maker': 'Maker',
    'exchanges.taker': 'Taker',
    'exchanges.deposit': 'Deposit',
    'exchanges.withdraw': 'Withdrawal',
    // Deep link to exchange app
    'deposit.label': 'Open',
    'deposit.title': 'Open exchange app',
    'deposit.confirmMessage': 'You will be redirected to the {exchange} app. Never share your credentials and always verify you are using the official app.',
    'deposit.openApp': 'Continue',
    'exchanges.confirmDelete': '⚠️ Confirm Deletion',
    'exchanges.confirmDisconnect': '⚠️ Confirm Disconnect',
    'exchanges.qrSuccess': '✅ Success!',
    'exchanges.qrLoaded': 'API Key and Secret loaded from QR Code!',
    'exchanges.qrFieldsLoaded': '{fields} loaded from QR Code!',
    'exchanges.qrFieldsExtracted': '{fields} extracted from QR Code!',
    'exchanges.apiKey': 'API Key',
    'exchanges.apiSecret': 'API Secret',
    'exchanges.passphrase': 'Passphrase',
    'exchanges.enterApiKey': 'Enter your API Key',
    'exchanges.enterApiSecret': 'Enter your API Secret',
    'exchanges.enterPassphrase': 'Enter your Passphrase',
    
    // Orders
    'orders.badge': 'Orders',
    'orders.title': 'Opens',
    'orders.empty': 'No open orders',
    'orders.emptyDescription': 'You have no open orders on your exchanges',
    'orders.emptyMessage': 'You have no open orders on this exchange',
    'orders.autoUpdate': 'Auto-update every 5 min',
    'orders.lastSync': 'Last update',
    'orders.loading': 'Loading orders...',
    'orders.error': 'Error loading orders',
    'orders.retry': 'Try again',
    'orders.noOrders': 'No open orders',
    'orders.oneOrder': '1 open order',
    'orders.multipleOrders': 'open orders',
    'orders.cancelAll': 'Cancel All',
    'orders.cancelAllTitle': '⚠️ Cancel All Orders',
    'orders.cancelAllMessage': 'Do you really want to cancel ALL {count} open order(s) on this exchange?',
    'orders.cancelAllWarning': '⚠️ This action cannot be undone!',
    'orders.cancelAllNo': 'No',
    'orders.cancelAllYes': 'Yes, Cancel All',
    'orders.cancel': 'Cancel',
    'orders.cancelling': 'Cancelling...',
    'orders.viewDetails': 'View Details',
    'orders.clone': 'Clone',
    'orders.cloneTitle': 'Clone Order',
    'orders.cloneMessage': 'Do you want to create a new order identical to this one?',
    'orders.cloneTooltip': 'Clone order',
    'orders.confirmClone': 'Yes, Clone',
    'orders.insufficientBalance': 'Insufficient balance for this order',
    'orders.loadingOrders': 'Loading orders...',

    // Alerts Modal
    'alerts.createTitle': '🔔 Create New Alert',
    'alerts.editTitle': '✏️ Edit Alert',
    'alerts.description': 'Set up a custom alert to be notified when a token reaches a certain variation or price.',
    'alerts.tokenLabel': 'Token (Symbol) *',
    'alerts.tokenPlaceholder': 'Ex: BTC, ETH, USDT',
    'alerts.exchangeLabel': 'Exchange (optional)',
    'alerts.exchangePlaceholder': 'Leave empty for all exchanges',
    'alerts.exchangeHelper': 'If left empty, the alert will work on all exchanges',
    'alerts.typeLabel': 'Alert Type',
    'alerts.typePercentage': '📊 Percentage Change (24h)',
    'alerts.typePrice': '💰 Absolute Price',
    'alerts.conditionLabel': 'Condition',
    'alerts.conditionAbove': '📈 Above (greater than or equal)',
    'alerts.conditionBelow': '📉 Below (less than or equal)',
    'alerts.valueLabel': 'Value *',
    'alerts.valuePercentage': '(%)',
    'alerts.valuePrice': '($)',
    'alerts.valuePlaceholderPercentage': 'Ex: -5 (for 5% drop)',
    'alerts.valuePlaceholderPrice': 'Ex: 50000 (for $50,000)',
    'alerts.valueHelperPercentage': 'Use negative values for drops (ex: -10) and positive for gains (ex: +10)',
    'alerts.valueHelperPrice': 'Enter the price in US dollars (USD)',
    'alerts.previewLabel': '📋 Alert Preview:',
    'alerts.previewText': 'You will be notified when',
    'alerts.previewOn': 'on',
    'alerts.previewWillBe': 'is',
    'alerts.previewAbove': 'above',
    'alerts.previewBelow': 'below',
    'alerts.previewVariation': 'change',
    'alerts.cancel': 'Cancel',
    'alerts.create': 'Create Alert',
    'alerts.update': 'Update',
    'alerts.saving': 'Saving...',
    
    // Token Monitor Notifications
    'tokenMonitor.falling': '{symbol} Falling',
    'tokenMonitor.fallingMessage': '{symbol} fell {percent}% in the last 24h. Price: ${price}',
    'tokenMonitor.rising': '🚀 {symbol} Rising',
    'tokenMonitor.risingMessage': '{symbol} rose {percent}% in the last 24h! Price: ${price}',
    'tokenMonitor.rapidChange': '⚡ {symbol} - Rapid Change',
    'tokenMonitor.rapidChangeMessage': '{symbol} {direction} rapidly. Variation: {variation}%. Price: ${price}',
    'tokenMonitor.rose': 'rose',
    'tokenMonitor.fell': 'fell',
    'tokenMonitor.below': '📉 {symbol} Below {value}%',
    'tokenMonitor.belowMessage': '{symbol} fell to {current}% (limit: {value}%). Price: ${price}',
    'tokenMonitor.above': '📈 {symbol} Above {value}%',
    'tokenMonitor.aboveMessage': '{symbol} rose to {current}% (limit: {value}%). Price: ${price}',
    'tokenMonitor.priceBelowTitle': '💰 {symbol} Below ${value}',
    'tokenMonitor.priceBelowMessage': '{symbol} reached ${current} (limit: ${value}). Variation: {variation}%',
    'tokenMonitor.priceAboveTitle': '💰 {symbol} Above ${value}',
    'tokenMonitor.priceAboveMessage': '{symbol} reached ${current} (limit: ${value}). Variation: {variation}%',
    
    'orders.order': 'order',
    'orders.ordersPlural': 'orders',
    'orders.timeAgo.minutes': '{minutes}m ago',
    'orders.timeAgo.hours': '{hours}h ago',
    'orders.timeAgo.days': '{days}d ago',
    'orders.edit': 'Edit',
    'orders.editTitle': 'Edit Order',
    'orders.newPrice': 'New Price',
    'orders.newAmount': 'New Amount',
    'orders.save': 'Save',
    'orders.editSuccess': 'Order edited successfully!',
    'orders.editError': 'Error editing order',
    'orders.price': 'Price',
    'orders.amount': 'Amount',
    'orders.filled': 'Filled',
    'orders.total': 'Total',
    'orders.type.limit': 'LIMIT',
    'orders.type.market': 'MARKET',
    'orders.type.stopLoss': 'STOP LOSS',
    'orders.side.buy': 'BUY',
    'orders.side.sell': 'SELL',
    'orders.details.status': 'Status',
    'orders.details.progress': 'Execution Progress',
    'orders.details.executed': 'executed',
    'orders.details.remaining': 'Remaining',
    'orders.details.title': 'Order Details',
    'orders.details.orderId': 'Order ID',
    'orders.details.totalCost': 'Total Cost',
    'orders.details.dateTime': 'Date/Time',
    'orders.details.fee': 'Fee',
    'orders.details.trades': 'Executed Trades',
    'orders.details.trade': 'Trade',
    'orders.details.close': 'Close',
    'orders.count': 'orders',
    'orders.countSingular': 'order',
    'orders.confirmCancel': 'Confirm Cancellation',
    'orders.cancelingOrder': 'Canceling order...',
    'orders.confirmCancelMessage': 'Are you sure you want to cancel this order?',
    'orders.pair': 'Pair',
    'orders.type': 'Type',
    'orders.exchange': 'Exchange',
    'orders.quantity': 'Quantity',
    'orders.cancelingAllOrders': 'Canceling all orders...',
    'orders.cancelFailed': 'Could not cancel',
    'orders.errorCode': 'Code',
    'orders.cancelOrder': 'Cancel Order',
    'orders.errorDetails': 'Error Details',
    'orders.fullResponse': 'Full response:',
    'orders.cancelConfirm': 'Do you really want to cancel this {side} order?',
    'orders.cancelBuy': 'buy',
    'orders.cancelSell': 'sell',
    'orders.cancelOrderError': 'Error cancelling order',
    'orders.unknownCancelError': 'Unknown error cancelling order',
    'orders.timeoutError': 'Timeout: Exchange did not respond in time',
    'orders.networkError': 'Network error: Check your connection',
    'orders.message': 'Message:',
    'orders.code': 'Code:',
    
    // Trade
    'trade.tooltip': 'Trade',
    'trade.title': 'Trade',
    'trade.buy': 'Buy',
    'trade.sell': 'Sell',
    'trade.creatingOrder': 'Creating order...',
    'trade.confirmBuy': 'Do you really want to buy',
    'trade.confirmSell': 'Do you really want to sell',
    
    // Exchanges tooltips and misc
    // 'exchanges.requiresPassphrase' moved up (line 579)
    
    // Token Details
    'token.details': 'Token Details',
    'token.currentPrice': 'Current Price',
    'token.priceVariation': 'Price Variation',
    'token.high24h': '24h High',
    'token.low24h': '24h Low',
    'token.volume24h': '24h Volume',
    'token.marketInfo': 'Market Information',
    'token.market': 'Market',
    'token.limits': 'Limits',
    'token.minAmount': 'Min Amount',
    'token.maxAmount': 'Max Amount',
    'token.minCost': 'Min Cost',
    'token.maxCost': 'Max Cost',
    'token.precision': 'Precision',
    'token.amountPrecision': 'Amount',
    'token.pricePrecision': 'Price',
    'token.bidPrice': 'Bid Price',
    'token.askPrice': 'Ask Price',
    'token.spread': 'Spread',
    'token.lastUpdate': 'Last update',
    'token.pair': 'Pair',
    'token.noData': 'Data not available',
    'token.loadingVariations': 'Loading variations...',
    'token.tokensIn': 'Tokens in',
    'token.totalIn': 'Total in',
    'token.exchanges': 'Exchanges',
    'token.amount': 'Amount:',
    'token.price': 'Price:',
    'token.total': 'Total:',
    'token.value': 'Value:',
    'token.viewDetails': 'View Details',
    'token.trade': 'Trade',
    'token.noBalance': 'No tokens with available balance',
    
    // Search
    'search.tokens': 'Search Tokens',
    'search.placeholder': 'Type token symbol or name...',
    'search.noResults': 'No tokens found',
    'search.startTyping': 'Type to search your tokens',
    
    // Common
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.refresh': 'Refresh',
    'common.tryAgain': 'Try Again',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.warning': 'Warning',
    'common.attention': 'Attention',
    'common.ok': 'OK',
    'common.next': 'Next',
    'common.create': 'Create',
    'common.viewDetails': 'View Details',
    'common.updatingData': 'Updating data...',
    'common.loadingTokens': 'Loading tokens...',
    'common.updated': 'Updated:',
    'common.updatedAt': 'Updated at {time}',
    'common.search': 'Search',
    'common.noResults': 'No results',
    'common.delete': 'Delete',
    'common.remove': 'Remove',
    'common.retry': 'Retry',
    'common.showMore': 'Show more',
    'common.showLess': 'Show less',
    
    // Error Messages
    'error.cameraAccess': 'Could not access the camera',
    'error.loadExchanges': 'Could not load your exchanges',
    'error.loadTokens': 'Could not load tokens',
    'error.createStrategy': 'Could not create strategy',
    'error.connectExchange': 'Could not connect exchange',
    'error.updateExchangeStatus': 'Could not update exchange status',
    'error.disconnectExchange': 'Could not disconnect exchange',
    'error.deleteExchange': 'Could not delete exchange',
    'error.pasteClipboard': 'Could not paste from clipboard',
    'error.fillAllFields': 'Please fill all fields',
    'error.fillApiKeys': 'Please fill API Key and API Secret',
    'error.passphraseRequired': 'This exchange requires a Passphrase',
    'error.loginFailed': 'Login failed',
    'error.biometricFailed': 'Biometric authentication failed',
    'error.unknownError': 'Unknown error',
    'error.invalidResponse': 'Invalid response format',
    
    // Success Messages
    'success.strategyCreated': 'Strategy created successfully!',
    'success.pastedClipboard': 'Pasted!',
    'success.textPasted': 'Text pasted from clipboard',
    
    // Warning Messages
    'warning.noTokensAvailable': 'This exchange has no tokens available',
    'warning.emptyClipboard': 'Empty clipboard',
    'warning.noClipboardText': 'No text in clipboard',
    
    // Exchange Alerts
    'alert.exchangeInactive': 'Inactive Exchange',
    
    // Auth (OAuth)
    'auth.completingLogin': 'Completing login...',
    
    // Maintenance Screen
    'maintenance.title': 'Under Maintenance',
    'maintenance.message': 'Our servers are temporarily unavailable. We are working to restore service as quickly as possible.',
    'maintenance.subMessage': 'We apologize for the inconvenience. Please try again in a few moments.',
    'maintenance.retry': 'Try Again',
    'maintenance.contact': 'If the problem persists, please contact support.',
    
    // Login Screen
    'login.welcome': 'Welcome!',
    'login.subtitle': 'Sign in to your account to continue',
    'login.email': 'Email',
    'login.emailPlaceholder': 'your@email.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.showPassword': 'Show',
    'login.hidePassword': 'Hide',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.orContinueWith': 'or continue with',
    'login.or': 'or',
    'login.signInWith': 'Sign in with',
    'login.google': 'Google',
    'login.apple': 'Apple',
    'login.noAccount': 'Don\'t have an account?',
    'login.signUp': 'Sign Up',
    'login.googleError': 'Failed to sign in with Google',
    'login.appleError': 'Failed to sign in with Apple',
    
    // SignUp Screen
    'signup.fillAllFields': 'Please fill in all fields',
    'signup.passwordMismatch': 'Passwords do not match',
    'signup.passwordTooShort': 'Password must be at least 6 characters',
    'signup.accountCreated': 'Account created successfully!',
    'signup.createAccountFailed': 'Failed to create account',
    'signup.googleSignupFailed': 'Failed to sign up with Google',
    'signup.appleSignupFailed': 'Failed to sign up with Apple',
    'signup.title': 'Create Account',
    'signup.subtitle': 'Start your journey today',
    'signup.nameLabel': 'Full name',
    'signup.namePlaceholder': 'John Doe',
    'signup.emailLabel': 'Email',
    'signup.emailPlaceholder': 'your@email.com',
    'signup.passwordLabel': 'Password',
    'signup.passwordPlaceholder': 'Minimum 6 characters',
    'signup.confirmPasswordLabel': 'Confirm password',
    'signup.confirmPasswordPlaceholder': 'Enter password again',
    'signup.showPassword': 'Show',
    'signup.hidePassword': 'Hide',
    'signup.termsText': 'By creating an account, you agree to our',
    'signup.termsOfService': 'Terms of Service',
    'signup.and': 'and',
    'signup.privacyPolicy': 'Privacy Policy',
    'signup.createButton': 'Create Account',
    'signup.orSignUpWith': 'or sign up with',
    'signup.google': 'Google',
    'signup.apple': 'Apple',
    'signup.alreadyHaveAccount': 'Already have an account?',
    'signup.signIn': 'Sign In',
    
    // Portfolio & Home Additional
    'portfolio.basedOnBalance': 'Portfolio based on exchange balances',
    'portfolio.updatedAt': 'Updated at',
    'portfolio.variationsNote': 'Variations are retrieved from exchanges',
    'portfolio.lastDays': 'Last {days} days',
    'portfolio.dailyPnl': 'DAILY PNL (TODAY)',
    'portfolio.today': 'TODAY',
    'portfolio.yesterday': 'Yesterday',
    'portfolio.noPnlData': 'Data unavailable',
    'portfolio.evolution': '{days}-day Evolution',
    'portfolio.noEvolutionData': 'No evolution data',
    'portfolio.day': 'day',
    'portfolio.days': 'days',
    
    // Settings Additional
    'settings.securityPrivacySection': 'Security Privacy',
    'settings.infoSectionTitle': 'Information',
    'settings.accountSection': 'Account',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountTitle': '⚠️ Confirm Deletion',
    'settings.deleteAccountWarning': 'WARNING: This action is IRREVERSIBLE!\n\nAre you absolutely sure you want to delete your account?',
    'settings.deleteAccountConfirm': 'WARNING: This action is IRREVERSIBLE!\n\nType "DELETE" to confirm account deletion:',
    'settings.deleteAccountSuccess': 'Account deleted successfully',
    'settings.deleteAccountButton': 'Delete',
    'settings.cancel': 'Cancel',
    
    // Profile
    'profile.logoutError': 'Could not complete logout',

    // Trade (extras)
    'trade.confirmOrder': 'Confirm Order',
    'trade.pair': 'Pair',
    'trade.side': 'Side',
    'trade.type': 'Type',
    'trade.price': 'Price',
    'trade.quantity': 'Quantity',
    'trade.totalToPay': 'Total to Pay',
    'trade.totalToReceive': 'Total to Receive',
    'trade.createStrategy': 'Create Strategy',

    // Watchlist
    'watchlist.noFavorites': 'No favorites yet',
    'watchlist.noFavoritesDesc': 'Mark tokens as favorites by tapping the star (⭐) in the assets list',
    'watchlist.noBalance': 'No balance',
    'watchlist.price': 'Price',
    'watchlist.totalValue': 'Total Value',
    'watchlist.viewDetails': 'View Details',
    'watchlist.trade': 'Trade',
    'watchlist.favoriteNoBalance': 'Favorite without balance',
    'watchlist.awaitingPrice': 'Token awaiting price query',
    'watchlist.status': 'Status',
    'watchlist.info': 'Info',

    // Alerts (simplified)
    'alerts.title': 'Alerts',
    'alerts.createAlert': 'Create Price Alert',
    'alerts.alertType': 'Alert Type',
    'alerts.absolutePrice': 'Absolute Price',
    'alerts.percentage': 'Percentage',
    'alerts.condition': 'Condition',
    'alerts.above': 'Above',
    'alerts.below': 'Below',
    'alerts.crossesUp': 'Crosses above',
    'alerts.crossesDown': 'Crosses below',
    'alerts.targetPrice': 'Target Price',
    'alerts.percentageLabel': 'Percentage',
    'alerts.frequency': 'Frequency',
    'alerts.once': 'Once',
    'alerts.always': 'Always',
    'alerts.daily': 'Daily',
    'alerts.customMessage': 'Custom Message',
    'alerts.previewAlert': 'Alert Preview:',
    'alerts.frequencyLabel': 'Frequency:',
    'alerts.createButton': 'Create Alert',
    'alerts.noAlerts': 'No alerts configured',
    'alerts.noAlertsDesc': 'Create your first price alert to receive notifications',
    'alerts.loadingAlerts': 'Loading alerts...',
    'alerts.removeAlert': 'Remove Alert',
    'alerts.triggered': 'Triggered',
    'alerts.currentPrice': 'Current price:',

    // Notifications (extras)
    'notifications.clearAll': 'Clear Notifications',
    'notifications.clearAllConfirm': 'Are you sure you want to remove all {count} notifications?',
    'notifications.clearAllButton': 'Clear All',
    'notifications.desc': 'Notifications and alerts',

    // Strategy (extras)
    'strategy.newTemplate': 'Create New Template',
    'strategy.customTemplate': 'Customize your own template',
    'strategy.noExchanges': 'No exchanges connected',
    'strategy.connectExchange': 'Connect an exchange in the "Exchanges" tab',
    'strategy.tapToChange': 'Tap to change',
    'strategy.summary': 'Strategy Summary',
    'strategy.connected': 'Connected',
    'strategy.protectionEnabled': 'Protection enabled',
    'strategy.searchToken': 'Search token (e.g. BTC, ETH, SOL...)',
    'strategy.results': '{count} result{plural}',
    'strategy.tokensAvailable': '{count} tokens available',
    'strategy.noTokenFound': 'No token found for "{query}"',
    'strategy.noTokenAvailable': 'No token available',

    // Market
    'market.currentPrice': 'Current Price',
    'market.change24h': '24h Change',
    'market.chartUnavailable': 'Chart unavailable',
    'market.apiTemporary': 'This may be a temporary API issue',

    // Assets
    'assets.availableOn': 'Available on {exchange}',
    'assets.searchingExchanges': 'Searching {query} on exchanges...',
    'assets.tokenNotFound': 'Token {symbol} not found',
    'assets.tokenNotFoundDesc': 'Could not find this token on connected exchanges or external APIs.',
    'assets.noTokenInExchange': 'No tokens in this exchange',

    // Token Details
    'tokenDetails.totalQuantity': 'Total Quantity',
    'tokenDetails.totalValueUsd': 'Total Value (USD)',

    // Pie Chart
    'chart.error': '⚠️ Error',
    'chart.fetchError': 'Failed to fetch balance',

    // Profile Menu
    'profileMenu.alerts': 'Alerts',
    'profileMenu.settings': 'Settings',
    'profileMenu.settingsDesc': 'Preferences and account',

    // Icon Selector
    'iconSelector.title': 'Select Icon',

    // QR Scanner
    'qr.requestingPermission': 'Requesting camera permission...',
    'qr.noAccess': 'No camera access',
    'qr.noAccessDesc': 'To scan QR codes, you need to allow camera access in your device settings.',

    // GenericItemList
    'genericList.noTokenInExchange': 'No tokens in this exchange',
    'genericList.item': 'item',
    'genericList.items': 'items',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en-US')
  const [isLoading, setIsLoading] = useState(true)

  // Load language from storage on mount
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY)
        if (savedLanguage === 'pt-BR' || savedLanguage === 'en-US') {
          setLanguage(savedLanguage)
        }
      } catch (error) {
        console.error('Error loading language:', error)
      } finally {
        setIsLoading(false)
      }
    }

    loadLanguage()
  }, [])

  // Save language to storage whenever it changes
  const handleSetLanguage = useCallback(async (newLanguage: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage)
      setLanguage(newLanguage)
    } catch (error) {
      console.error('Error saving language:', error)
      // Still update the state even if storage fails
      setLanguage(newLanguage)
    }
  }, [])

  // Translation function
  const t = useCallback((key: string): string => {
    return translations[language][key as keyof typeof translations['pt-BR']] || key
  }, [language])

  // Memoize context value
  const value = useMemo(() => ({
    language,
    setLanguage: handleSetLanguage,
    t,
    isLoading
  }), [language, handleSetLanguage, t, isLoading])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
